name: CI-Test

on: push

jobs:
  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.2
      - name: check branch
        run: pwd && ls -l 
