name: CI-Test

on: push

jobs:
  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: check branch
        run: | 
          git branch
          git log 
